#!/bin/bash

name="lucastorterotot PhD Thesis"

echo "Installing $name..."

instal_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

bin_dir=$instal_dir/bin/
if [[ $PATH = *$bin_dir* ]] || [[ $(grep -l "$name" ~/.bashrc) = ~/.bashrc ]]
then
    echo 'It seems like you already have installed this!'
    echo 'Not changing anything.'
else
    if [[ $instal_dir = $HOME* ]]
    then
        instal_dir=~${instal_dir#$HOME}
    fi
    echo "" >> ~/.bashrc
    echo "# --- add $name ---" >> ~/.bashrc
    echo ". $instal_dir/bashrc_ext" >> ~/.bashrc
    echo "Installation completed."
fi
